cd j1280
sh ../../../../scripts/gasave.do
cd ..
cd j160
sh ../../../../scripts/gasave.do
cd ..
cd j20
sh ../../../../scripts/gasave.do
cd ..
cd j2560
sh ../../../../scripts/gasave.do
cd ..
cd j30
sh ../../../../scripts/gasave.do
cd ..
cd j320
sh ../../../../scripts/gasave.do
cd ..
cd j40
sh ../../../../scripts/gasave.do
cd ..
cd j50
sh ../../../../scripts/gasave.do
cd ..
cd j60
sh ../../../../scripts/gasave.do
cd ..
cd j640
sh ../../../../scripts/gasave.do
cd ..
cd j80
sh ../../../../scripts/gasave.do
